apiVersion: v1
kind: Pod
metadata:
  name: clusterip-dnat
  labels:
    name: clusterip-dnat
spec:
  nodeName: k8s-w1
  containers:
  - name: whoami
    image: traefik/whoami
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: clusterip-dnat
spec:
  selector:
    name: clusterip-dnat
  ports:
  - port: 80
    targetPort: 80
