apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nodeport-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-nodeport-test
  template:
    metadata:
      labels:
        app: nginx-nodeport-test
    spec:
      containers:
      - name: netshoot
        image: nicolaka/netshoot
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-test
spec:
  type: NodePort
  selector:
    app: nginx-nodeport-test
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
