apiVersion: v1
kind: Pod
metadata:
  name: same-namespace
spec:
  containers:
  - name: container1
    image: nginx
    ports:
      - containerPort: 80
  - name: netshoot
    image: nicolaka/netshoot
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
